/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ActorType = "api_key_client" | "organization_account";

export type EnvironmentType = "development" | "production" | "staging";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InstanceControlSignal = "pause" | "terminate";

export type InstanceEntityType = "instance" | "task" | "task_execution" | "user_task_execution";

export type InstanceEventType = "completed" | "failed" | "pause_requested" | "paused" | "resume_requested" | "resumed" | "retried" | "started" | "terminate_requested" | "terminated";

export type InstanceStatus = "completed" | "failed" | "in_progress" | "paused" | "terminated";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type NodeType = "decision" | "email" | "end" | "script" | "service" | "start" | "user";

export type SecretProviderType = "aws_secrets_manager" | "default" | "infisical";

export type TaskStatus = "completed" | "failed" | "in_progress" | "paused" | "terminated";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkflowVersionStatus = "active" | "draft" | "published" | "valid";

export interface Actor {
  id: Generated<string>;
  type: ActorType;
}

export interface ApiKey {
  actor_id: string;
  created_on: Generated<Timestamp>;
  deleted_on: Timestamp | null;
  environment_id: string;
  id: Generated<string>;
  is_deleted: Generated<boolean | null>;
  is_revoked: Generated<boolean>;
  key_hash: string;
  key_prefix: string;
  label: string;
  modified_on: Generated<Timestamp>;
  revoked_on: Timestamp | null;
}

export interface Edge {
  client_id: string;
  condition_expression: string | null;
  created_by: string;
  created_on: Generated<Timestamp>;
  deleted_by: string | null;
  deleted_on: Timestamp | null;
  destination_node_id: string | null;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  modified_by: string;
  modified_on: Generated<Timestamp>;
  name: string | null;
  rule_id: string | null;
  source_node_id: string;
}

export interface Environment {
  created_on: Generated<Timestamp>;
  deleted_on: Timestamp | null;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  organization_id: string;
  type: EnvironmentType;
}

export interface Instance {
  auto_advance: Generated<boolean>;
  control_signal: InstanceControlSignal | null;
  created_by: string;
  created_on: Generated<Timestamp>;
  current_node_id: string | null;
  current_variables: Json | null;
  ended_on: Timestamp | null;
  id: Generated<string>;
  input_variables: Json | null;
  is_deleted: Generated<boolean>;
  output_variables: Json | null;
  started_on: Timestamp | null;
  status: InstanceStatus;
  workflow_version_id: string;
}

export interface InstanceLog {
  created_by: string | null;
  created_on: Generated<Timestamp>;
  details: Json | null;
  entity_id: string;
  entity_type: InstanceEntityType;
  event_type: InstanceEventType;
  id: Generated<string>;
  instance_id: string;
}

export interface Node {
  client_id: string;
  configuration: Json;
  created_by: string;
  created_on: Generated<Timestamp>;
  deleted_by: string | null;
  deleted_on: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  input_schema: Json | null;
  is_deleted: Generated<boolean>;
  max_attempts: Generated<number>;
  modified_by: string;
  modified_on: Generated<Timestamp>;
  name: string | null;
  output_schema: Json | null;
  type: NodeType;
  workflow_version_id: string;
  x_coordinate: number | null;
  y_coordinate: number | null;
}

export interface Organization {
  actor_id: string;
  created_on: Generated<Timestamp>;
  deleted_on: Timestamp | null;
  email: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  modified_on: Generated<Timestamp>;
  name: string;
  password_hash: string;
}

export interface RefreshToken {
  created_on: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  organization_id: string | null;
  token: string;
}

export interface SecretProvider {
  configuration: Json;
  created_on: Generated<Timestamp | null>;
  id: Generated<string>;
  label: string | null;
  organization_id: string;
  type: SecretProviderType;
  updated_on: Generated<Timestamp | null>;
}

export interface SecretReference {
  created_on: Generated<Timestamp | null>;
  environment_id: string;
  id: Generated<string>;
  label: string;
  provider_id: string;
  secret_key: string;
}

export interface Task {
  created_on: Generated<Timestamp>;
  id: Generated<string>;
  instance_id: string;
  node_id: string;
  status: TaskStatus;
}

export interface TaskExecution {
  created_on: Generated<Timestamp>;
  ended_on: Timestamp | null;
  id: Generated<string>;
  input_variables: Json | null;
  output_variables: Json | null;
  started_on: Timestamp | null;
  status: TaskStatus;
  task_id: string;
}

export interface UserTaskExecution {
  assignee: string | null;
  created_on: Generated<Timestamp>;
  id: Generated<string>;
  task_execution_id: string;
  title: string | null;
}

export interface Workflow {
  base_workflow_id: string | null;
  created_by: string;
  created_on: Generated<Timestamp>;
  deleted_by: string | null;
  deleted_on: Timestamp | null;
  description: string | null;
  environment_id: string;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  modified_by: string;
  modified_on: Generated<Timestamp>;
  name: string;
}

export interface WorkflowVersion {
  created_by: string;
  created_on: Generated<Timestamp>;
  deleted_by: string | null;
  deleted_on: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  modified_by: string;
  modified_on: Generated<Timestamp>;
  published_on: Timestamp | null;
  status: WorkflowVersionStatus;
  version: number;
  workflow_id: string;
}

export interface DB {
  actor: Actor;
  api_key: ApiKey;
  edge: Edge;
  environment: Environment;
  instance: Instance;
  instance_log: InstanceLog;
  node: Node;
  organization: Organization;
  refresh_token: RefreshToken;
  secret_provider: SecretProvider;
  secret_reference: SecretReference;
  task: Task;
  task_execution: TaskExecution;
  user_task_execution: UserTaskExecution;
  workflow: Workflow;
  workflow_version: WorkflowVersion;
}
